In [1]:
import os
import glob
import pandas as pd
import numpy as np
from multiprocessing import Pool

In [26]:
def describe_boxplot(df_series):
    min_value = df_series.min()
    max_value = df_series.max()
    df_res = df_series.quantile([0.25, 0.5, 0.75])
    print("N\t%d" % len(df_series))
    print("min\t%f" % min_value)
    print("max\t%f" % max_value)
    print(df_res)

In [38]:
def figure_2c():
    x = "/home/xialj/data6/xlj/Differential_m6A/Ratio/DMR/Binji/Filter_FPKM0/Expression/Data_for_plot/data_forplot"
    df = pd.read_table(x, sep="\t")
#     print(df.head())
    organ_list = list(set(df["Organ"].tolist()))
    for organ in organ_list:
        print("#### %s #####" % organ)
        df_sub = df[df.Organ == organ]
        df_c = df_sub[df_sub.Type == "Constitutive m(6)As"]
        df_d = df_sub[df_sub.Type == "Differential m(6)As"]
        print("^^^ Constitutive m(6)As ^^^")
        describe_boxplot(df_c["value"])
        print("^^^ Differential m(6)As ^^^")
        describe_boxplot(df_d["value"])
        print()
figure_2c()

#### Muscle #####
^^^ Constitutive m(6)As ^^^
N	14140
min	0.004956
max	9.967370
0.25    1.281266
0.50    2.595884
0.75    3.620366
Name: value, dtype: float64
^^^ Differential m(6)As ^^^
N	677
min	0.015502
max	6.422870
0.25    0.412889
0.50    1.328710
0.75    2.643468
Name: value, dtype: float64

#### Stomach #####
^^^ Constitutive m(6)As ^^^
N	12397
min	0.009058
max	11.480174
0.25    1.541971
0.50    2.702793
0.75    3.657034
Name: value, dtype: float64
^^^ Differential m(6)As ^^^
N	353
min	0.024171
max	7.468054
0.25    0.782789
0.50    1.833105
0.75    3.089464
Name: value, dtype: float64

#### Lung #####
^^^ Constitutive m(6)As ^^^
N	13071
min	0.003215
max	10.470008
0.25    0.972943
0.50    2.309013
0.75    3.498997
Name: value, dtype: float64
^^^ Differential m(6)As ^^^
N	409
min	0.007394
max	9.676625
0.25    0.266958
0.50    0.973428
0.75    2.699860
Name: value, dtype: float64

#### Heart #####
^^^ Constitutive m(6)As ^^^
N	13356
min	0.002460
max	11.695985
0.25    1.412883
0.50    2.557550
0.75    3.541874
Name: value, dtype: float64
^^^ Differential m(6)As ^^^
N	568
min	0.008798
max	9.341332
0.25    0.377486
0.50    1.161955
0.75    2.666911
Name: value, dtype: float64

#### Brain #####
^^^ Constitutive m(6)As ^^^
N	14338
min	0.005002
max	10.595183
0.25    1.420527
0.50    2.637148
0.75    3.624753
Name: value, dtype: float64
^^^ Differential m(6)As ^^^
N	566
min	0.008969
max	7.146869
0.25    0.586768
0.50    2.122576
0.75    3.380803
Name: value, dtype: float64

#### Liver #####
^^^ Constitutive m(6)As ^^^
N	13470
min	0.003726
max	11.920993
0.25    1.388355
0.50    2.589843
0.75    3.634608
Name: value, dtype: float64
^^^ Differential m(6)As ^^^
N	571
min	0.007771
max	7.374448
0.25    0.288434
0.50    0.898900
0.75    2.390580
Name: value, dtype: float64

#### Kidney #####
^^^ Constitutive m(6)As ^^^
N	17229
min	0.004158
max	11.150947
0.25    1.295888
0.50    2.586717
0.75    3.567545
Name: value, dtype: float64
^^^ Differential m(6)As ^^^
N	377
min	0.006749
max	7.319907
0.25    0.521490
0.50    1.329370
0.75    2.674562
Name: value, dtype: float64

#### Placenta #####
^^^ Constitutive m(6)As ^^^
N	14804
min	0.009148
max	10.658881
0.25    1.012165
0.50    2.208797
0.75    3.241269
Name: value, dtype: float64
^^^ Differential m(6)As ^^^
N	769
min	0.007301
max	10.692511
0.25    0.486550
0.50    1.519627
0.75    2.786843
Name: value, dtype: float64

In [39]:
def figure_4a():
    x = "/home/xialj/data6/xlj/Gene_Expression_divergence/gene_methylation_level/Rank_m6A_number/Result.txt"
    df = pd.read_table(x, sep="\t", skiprows=2)
    term_list = list(set(df["type"].tolist()))
    for term in term_list:
        print("#### %s #####" % term)
        df_sub = df[df.type == term]
        describe_boxplot(df_sub["cv"])
figure_4a()

#### L #####
N	3214
min	0.070843
max	2.640755
0.25    0.494657
0.50    0.843786
0.75    1.531489
Name: cv, dtype: float64
#### H #####
N	11776
min	0.053122
max	2.635691
0.25    0.264381
0.50    0.421362
0.75    0.682357
Name: cv, dtype: float64
#### M #####
N	3666
min	0.070622
max	2.628101
0.25    0.401614
0.50    0.719515
0.75    1.206389
Name: cv, dtype: float64

In [40]:
def figure_4b():
    x = "/home/xialj/data6/xlj/Gene_Expression_divergence/gene_methylation_level/Rank_expCV/data_for_plot"
    df = pd.read_table(x, sep="\t")
    term_list = list(set(df["type"].tolist()))
    for term in term_list:
        print("#### %s #####" % term)
        df_sub = df[df.type == term]
        describe_boxplot(df_sub["ratio"])
figure_4b()

#### High #####
N	9127
min	0.000000
max	1.000000
0.25    0.375
0.50    0.625
0.75    1.000
Name: ratio, dtype: float64
#### Low #####
N	9356
min	0.000000
max	1.000000
0.25    0.75
0.50    1.00
0.75    1.00
Name: ratio, dtype: float64

In [31]:
def figure_4c_mRNA():
    x = "/home/xialj/data6/xlj/Gene_Expression_divergence/gene_methylation_level/Rank_m6A_number/mRNA/Result.txt"
    df = pd.read_table(x, sep="\t", skiprows=2)
    term_list = list(set(df["type"].tolist()))
    for term in term_list:
        print("#### %s #####" % term)
        df_sub = df[df.type == term]
        describe_boxplot(df_sub["cv"])
print("############################  mRNA  #############################")
figure_4c_mRNA()
print()
######################
def figure_4c_lincRNA():
    x = "/home/xialj/data6/xlj/Gene_Expression_divergence/gene_methylation_level/Rank_m6A_number/lincRNA/Result.txt"
    df = pd.read_table(x, sep="\t", skiprows=2)
    term_list = list(set(df["type"].tolist()))
    for term in term_list:
        print("#### %s #####" % term)
        df_sub = df[df.type == term]
        describe_boxplot(df_sub["cv"])
print("############################  lincRNA  #############################")
figure_4c_lincRNA()

############################  mRNA  #############################
#### L #####
N	1865
min	0.070843
max	2.640755
0.25    0.527442
0.50    1.082917
0.75    1.905846
Name: cv, dtype: float64
#### H #####
N	10150
min	0.053122
max	2.635691
0.25    0.253224
0.50    0.402155
0.75    0.677360
Name: cv, dtype: float64
#### M #####
N	2629
min	0.070622
max	2.628101
0.25    0.377285
0.50    0.778452
0.75    1.329806
Name: cv, dtype: float64

############################  lincRNA  #############################
#### L #####
N	388
min	0.211314
max	2.612076
0.25    0.596054
0.50    0.815748
0.75    1.177893
Name: cv, dtype: float64
#### H #####
N	296
min	0.136698
max	2.605483
0.25    0.368831
0.50    0.497627
0.75    0.693143
Name: cv, dtype: float64
#### M #####
N	277
min	0.150721
max	2.499978
0.25    0.506916
0.50    0.763168
0.75    1.073840
Name: cv, dtype: float64

In [32]:
def figure_4d_mRNA():
    x = "/home/xialj/data6/xlj/Gene_Expression_divergence/gene_methylation_level/Rank_m6A_level/mRNA/data_for_plot"
    df = pd.read_table(x, sep="\t")
    term_list = list(set(df["type"].tolist()))
    for term in term_list:
        print("#### %s #####" % term)
        df_sub = df[df.type == term]
        describe_boxplot(df_sub["cv"])
print("############################  mRNA  #############################")
figure_4d_mRNA()
print()
######################
def figure_4d_lincRNA():
    x = "/home/xialj/data6/xlj/Gene_Expression_divergence/gene_methylation_level/Rank_m6A_level/lincRNA/data_for_plot"
    df = pd.read_table(x, sep="\t")
    term_list = list(set(df["type"].tolist()))
    for term in term_list:
        print("#### %s #####" % term)
        df_sub = df[df.type == term]
        describe_boxplot(df_sub["ratio"])
print("############################  lincRNA  #############################")
figure_4d_lincRNA()

############################  mRNA  #############################
#### High #####
N	7317
min	0.062276
max	2.635691
0.25    0.279718
0.50    0.482720
0.75    0.818531
Name: cv, dtype: float64
#### Low #####
N	7304
min	0.053122
max	2.640755
0.25    0.272998
0.50    0.495858
0.75    1.017527
Name: cv, dtype: float64

############################  lincRNA  #############################
#### High #####
N	471
min	0.146893
max	2.608751
0.25    0.434549
0.50    0.617155
0.75    0.924299
Name: ratio, dtype: float64
#### Low #####
N	471
min	0.136698
max	2.612076
0.25    0.536091
0.50    0.746624
0.75    1.090027
Name: ratio, dtype: float64

In [35]:
def figure_extended_4():
    x = "/home/xialj/data6/xlj/Gene_Expression_divergence/gene_methylation_level/Rank_m6A_number/Transcript_region/gene_methylation/Result.txt"
    df = pd.read_table(x, sep="\t", skiprows=5)
    organ_list = list(set(df["region"].tolist()))
    for organ in organ_list:
        print()
        print("#### %s #####" % organ)
        df_sub = df[df.region == organ]
        df_a = df_sub[df_sub.type == "L"]
        df_b = df_sub[df_sub.type == "M"]
        df_c = df_sub[df_sub.type == "H"]
        print("^^^^ L ^^^^")
        describe_boxplot(df_a["cv"])
        print("^^^^ M ^^^^")
        describe_boxplot(df_b["cv"])
        print("^^^^ H ^^^^")
        describe_boxplot(df_c["cv"])
figure_extended_4()

#### CDS #####
^^^^ L ^^^^
N	3071
min	0.063380
max	2.640006
0.25    0.303257
0.50    0.621913
0.75    1.211064
Name: cv, dtype: float64
^^^^ M ^^^^
N	2245
min	0.062276
max	2.623019
0.25    0.286419
0.50    0.518704
0.75    0.962409
Name: cv, dtype: float64
^^^^ H ^^^^
N	3620
min	0.063537
max	2.595642
0.25    0.255289
0.50    0.399839
0.75    0.637100
Name: cv, dtype: float64

#### Stop_codon #####
^^^^ L ^^^^
N	2125
min	0.053122
max	2.640755
0.25    0.385344
0.50    0.758494
0.75    1.519370
Name: cv, dtype: float64
^^^^ M ^^^^
N	1909
min	0.073201
max	2.595642
0.25    0.311211
0.50    0.589158
0.75    1.057798
Name: cv, dtype: float64
^^^^ H ^^^^
N	4489
min	0.063380
max	2.587893
0.25    0.247005
0.50    0.397860
0.75    0.663084
Name: cv, dtype: float64

#### 3-UTR #####
^^^^ L ^^^^
N	2406
min	0.062276
max	2.639426
0.25    0.334532
0.50    0.629913
0.75    1.207402
Name: cv, dtype: float64
^^^^ M ^^^^
N	1647
min	0.070622
max	2.583885
0.25    0.298917
0.50    0.543134
0.75    0.878489
Name: cv, dtype: float64
^^^^ H ^^^^
N	1621
min	0.053122
max	2.424490
0.25    0.256041
0.50    0.422397
0.75    0.675157
Name: cv, dtype: float64

#### 5-UTR #####
^^^^ L ^^^^
N	2935
min	0.062276
max	2.637874
0.25    0.312111
0.50    0.571114
0.75    1.073767
Name: cv, dtype: float64
^^^^ M ^^^^
N	1984
min	0.053122
max	2.595642
0.25    0.273535
0.50    0.449072
0.75    0.759659
Name: cv, dtype: float64
^^^^ H ^^^^
N	1662
min	0.056254
max	2.415936
0.25    0.235190
0.50    0.367495
0.75    0.580802
Name: cv, dtype: float64

In [36]:
def figure_6a():
    x = "/home/galaxy/project/revised_version/project/CpG_density/m6a_vs_free/m6a_vs_free.txt"
    df = pd.read_table(x, sep="\t", header=None, names=["Organ", "type", "value"])
    organ_list = list(set(df["Organ"].tolist()))
    for organ in organ_list:
        print("#### %s #####" % organ)
        df_sub = df[df.Organ == organ]
        df_c = df_sub[df_sub.type == "m6a"]
        df_d = df_sub[df_sub.type == "free"]
        print("^^^^ m6a ^^^^")
        describe_boxplot(df_c["value"])
        print("^^^^ free ^^^^")
        describe_boxplot(df_d["value"])
        print()
figure_6a()

#### heart #####
^^^^ m6a ^^^^
N	11600
min	0.039679
max	1.180764
0.25    0.347994
0.50    0.501526
0.75    0.626323
Name: value, dtype: float64
^^^^ free ^^^^
N	7070
min	0.041189
max	1.287161
0.25    0.224445
0.50    0.358157
0.75    0.539730
Name: value, dtype: float64

#### muscle #####
^^^^ m6a ^^^^
N	11906
min	0.039679
max	1.287161
0.25    0.342919
0.50    0.500283
0.75    0.627107
Name: value, dtype: float64
^^^^ free ^^^^
N	5462
min	0.042154
max	1.084004
0.25    0.237226
0.50    0.382495
0.75    0.546590
Name: value, dtype: float64

#### stomach #####
^^^^ m6a ^^^^
N	10498
min	0.039679
max	1.180764
0.25    0.346829
0.50    0.502320
0.75    0.628827
Name: value, dtype: float64
^^^^ free ^^^^
N	6799
min	0.042154
max	1.287161
0.25    0.247991
0.50    0.402312
0.75    0.563477
Name: value, dtype: float64

#### placenta #####
^^^^ m6a ^^^^
N	12642
min	0.039679
max	1.287161
0.25    0.340456
0.50    0.497240
0.75    0.622826
Name: value, dtype: float64
^^^^ free ^^^^
N	5130
min	0.041189
max	1.180764
0.25    0.226586
0.50    0.358592
0.75    0.539985
Name: value, dtype: float64

#### brain #####
^^^^ m6a ^^^^
N	12074
min	0.039679
max	1.287161
0.25    0.357006
0.50    0.506900
0.75    0.628815
Name: value, dtype: float64
^^^^ free ^^^^
N	7721
min	0.036828
max	1.138163
0.25    0.209609
0.50    0.322289
0.75    0.506759
Name: value, dtype: float64

#### kidney #####
^^^^ m6a ^^^^
N	13675
min	0.039679
max	1.287161
0.25    0.338179
0.50    0.494899
0.75    0.621889
Name: value, dtype: float64
^^^^ free ^^^^
N	4758
min	0.041189
max	1.138163
0.25    0.213075
0.50    0.324403
0.75    0.511432
Name: value, dtype: float64

#### lung #####
^^^^ m6a ^^^^
N	11050
min	0.039679
max	1.180764
0.25    0.344245
0.50    0.499742
0.75    0.626832
Name: value, dtype: float64
^^^^ free ^^^^
N	6511
min	0.041189
max	1.287161
0.25    0.240640
0.50    0.393263
0.75    0.557684
Name: value, dtype: float64

#### liver #####
^^^^ m6a ^^^^
N	11530
min	0.039679
max	1.287161
0.25    0.346280
0.50    0.501014
0.75    0.624567
Name: value, dtype: float64
^^^^ free ^^^^
N	6494
min	0.041189
max	1.135147
0.25    0.235103
0.50    0.373003
0.75    0.547088
Name: value, dtype: float64