In [9]:
import os
import glob
import pandas as pd
from scipy import stats
from collections import Counter

#### MatrixEQTL results

In [14]:
qtl_dir = "/home/galaxy/project/m6AQTL/2019_10_10/transcriptome_snp/SNPiR/shell/all_samples/results/MatrixEQTL_result"
cis_file = os.path.join(qtl_dir, "m6AQTL_cis_linear_v8.txt")

In [15]:
df_cis = pd.read_table(cis_file)
df_cis.head()

,SNP,gene,beta,t-stat,p-value,FDR
0,chr5:1332962,chr5:471218-471318,-0.302552,-42.500014,1.295564e-22,2.816771e-15
1,chr19:4008190,chr19:4961456-4961581,-0.580429,-29.633439,3.161923e-19,2.340354e-12
2,chr19:2422211,chr19:1827170-1827345,-0.514327,-29.604364,3.229314e-19,2.340354e-12
3,chr19:2422211,chr19:1827545-1827695,-0.410427,-28.966954,5.153335e-19,2.572938e-12
4,chr19:1184494,chr19:1206264-1206664,-0.612125,-28.780995,5.917071e-19,2.572938e-12

In [22]:
snp_m6a_dict = dict(zip(df_cis["SNP"], df_cis["gene"]))
print(snp_m6a_dict["chr19:1184494"])

chr19:1206814-1206989

#### SNP genotype (AA, AB, BB)

In [2]:
snp_dir = "/home/galaxy/project/m6AQTL/2019_10_10/transcriptome_snp/SNPiR/shell/all_samples/results/MatrixEQTL_result"
snp_file = os.path.join(snp_dir, "final_SNP_reorder.csv")

In [7]:
df_snp = pd.read_csv(snp_file, index_col=0)
df_snp.head()

,SRR7075101,SRR1811018,SRR1811012,SRR1182601,SRR1182599,SRR1182597,SRR1182595,SRR1182587-88,SRR1182582-84,SRR5978883-89,...,SRR494616,SRR494614,SRR5934169,SRR456936,SRR7130854,SRR7130859,SRR7130862,SRR7130864,SRR7130867,SRR7130874
id,,,,,,,,,,,,,,,,,,,,,
chr1:15774,0,1,0,1,1,1,1,1,1,0,...,0,0,0,1,0,0,1,1,0,0
chr1:64649,0,0,1,1,1,1,1,0,1,0,...,0,0,0,0,1,0,1,1,0,1
chr1:67631,0,0,1,1,0,1,1,1,1,0,...,0,0,0,0,1,0,0,0,0,1
chr1:70317,0,0,1,1,0,1,0,1,1,0,...,0,0,0,0,0,0,1,0,0,1
chr1:78942,0,1,0,0,0,1,0,1,1,0,...,0,0,0,1,1,0,1,1,0,1

In [10]:
col_list = df_snp.columns
sample_dict = {}

for index, values in df_snp.iterrows():
    count = Counter(values)
    if (count[1] >1) and (count[2] >1):
        ref_homo_list = [i for i in range(len(values)) if values[i] == 0]
        alt_homo_list = [i for i in range(len(values)) if values[i] == 2]
        sample_dict[index] = [ref_homo_list, alt_homo_list]

In [11]:
sample_dict["chr1:725401"]

[[0,
  1,
  2,
  5,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  19,
  21,
  22,
  23,
  24,
  27,
  28,
  30],
 [17, 18, 20]]

In [12]:
matrix_dir = "/home/galaxy/project/m6AQTL/2019_10_10/transcriptome_snp/SNPiR/shell/all_samples/results/quantification"
matrix_file = os.path.join(matrix_dir, "bedtools_quantification.matrix")

In [13]:
df_m6a = pd.read_table(matrix_file)
df_m6a.head()

,SRR7075101,SRR1811018,SRR1811012,SRR1182601,SRR1182599,SRR1182597,SRR1182595,SRR1182587-88,SRR1182582-84,SRR5978883-89,...,SRR494616,SRR494614,SRR5934169,SRR456936,SRR7130854,SRR7130859,SRR7130862,SRR7130864,SRR7130867,SRR7130874
chr2:70471573-70471648,1.000000,1.000000,1.240328,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,0.887140,0.699081,1.000000,0.771893,0.868192,0.748143,0.676308,1.000000,1.000000
chr6:3122960-3123910,0.968491,0.994113,0.994777,1.151600,0.909753,1.069524,0.819255,0.879231,0.923858,1.045308,...,0.826320,0.791340,0.863966,0.984942,0.671559,0.826811,0.769021,0.638590,0.826279,0.917816
chr13:111783550-111783600,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,0.902843,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
chr17:2282821-2283121,1.032080,1.425973,1.336861,0.738352,1.133137,1.000000,1.236198,0.968794,1.121328,0.942592,...,0.806126,0.973292,0.656183,1.000000,0.457486,0.474092,0.479401,0.516185,0.408739,0.614962
chr3:127292343-127292418,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [24]:
result_dir = "/home/galaxy/project/m6AQTL/2019_10_10/transcriptome_snp/SNPiR/shell/all_samples/results/diff_methylation"
with open("%s/snp_m6a.data" % result_dir, 'w') as fw:
    for snp, index_array in sample_dict.items():
        ref_list, alt_list = index_array[0], index_array[1]
        if snp in snp_m6a_dict:
            m6a_id = snp_m6a_dict[snp]
            m6a_values = df_m6a.loc[m6a_id, :]
            ref_values, alt_values = [str(m6a_values[i]) for i in ref_list], [str(m6a_values[i]) for i in alt_list]
            fw.write("%s\t%s\t%s\t%s\n" % (snp, m6a_id, ",".join(ref_values), ",".join(alt_values)))

#### T-test

In [27]:
r_dir="/home/galaxy/project/m6AQTL/2019_10_10/transcriptome_snp/SNPiR/shell/all_samples/results/diff_methylation"
in_file = "%s/snp_m6a.data" % r_dir
out_file = "%s/ttest.result" % r_dir
with open(out_file, 'w') as fw:
    fw.write("SNP\tm6A\tref_median\talt_median\tt-stat\tpvalue\n")
    with open(in_file, 'r') as f:
        for line in f.readlines():
            prefix = "\t".join(line.split("\t")[0:2])
            ref_list, alt_list = line.split("\t")[2].split(","), line.split("\t")[3].split(",")
            ref_values, alt_values = [float(x) for x in ref_list], [float(x) for x in alt_list]
            ref_median, alt_median = np.median(ref_values), np.median(alt_values)
            t_stat, pvalue = stats.ttest_ind(ref_values, alt_values)
            fw.write("%s\t%s\t%s\t%s\t%s\n" % (prefix, str(ref_median), str(alt_median), str(t_stat), str(pvalue)))